"""initial migration

Revision ID: c59a25ec6482
Revises: 
Create Date: 2026-03-30 20:22:17.038408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c59a25ec6482'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_banks_slug'), 'banks', ['slug'], unique=True)
    op.create_table('deposit_open_methods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deposit_open_methods_code'), 'deposit_open_methods', ['code'], unique=True)
    op.create_table('deposit_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deposit_products_bank_id'), 'deposit_products', ['bank_id'], unique=False)
    op.create_table('deposit_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('allow_topup', sa.Boolean(), nullable=False),
    sa.Column('allow_partial_withdraw', sa.Boolean(), nullable=False),
    sa.Column('auto_prolongation', sa.Boolean(), nullable=False),
    sa.Column('min_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('max_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('min_term_days', sa.Integer(), nullable=False),
    sa.Column('max_term_days', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('max_amount IS NULL OR max_amount >= min_amount', name='ck_variant_max_amount_gte_min_amount'),
    sa.CheckConstraint('max_term_days IS NULL OR max_term_days >= min_term_days', name='ck_variant_max_term_gte_min_term'),
    sa.CheckConstraint('min_amount >= 0', name='ck_variant_min_amount_non_negative'),
    sa.CheckConstraint('min_term_days > 0', name='ck_variant_min_term_positive'),
    sa.ForeignKeyConstraint(['product_id'], ['deposit_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deposit_variants_code'), 'deposit_variants', ['code'], unique=False)
    op.create_index(op.f('ix_deposit_variants_product_id'), 'deposit_variants', ['product_id'], unique=False)
    op.create_table('deposit_constraints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('constraint_type', sa.Enum('TOPUP_RULE', 'AMOUNT_CAP_RULE', 'EARLY_TERMINATION_RULE', 'PROLONGATION_RULE', 'WITHDRAW_RULE', 'OTHER', name='constrainttypeenum'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('params_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['variant_id'], ['deposit_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_constraints_variant_type', 'deposit_constraints', ['variant_id', 'constraint_type'], unique=False)
    op.create_index(op.f('ix_deposit_constraints_variant_id'), 'deposit_constraints', ['variant_id'], unique=False)
    op.create_table('deposit_early_termination_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('nominal_rate', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('effective_rate', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('params_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['variant_id'], ['deposit_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deposit_early_termination_rules_variant_id'), 'deposit_early_termination_rules', ['variant_id'], unique=False)
    op.create_table('deposit_fees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('fee_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount_fixed', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('amount_percent', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('params_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['variant_id'], ['deposit_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deposit_fees_variant_id'), 'deposit_fees', ['variant_id'], unique=False)
    op.create_table('deposit_interest_schemes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('payout_type', sa.String(length=50), nullable=False),
    sa.Column('payout_frequency', sa.String(length=50), nullable=True),
    sa.Column('capitalization_enabled', sa.Boolean(), nullable=False),
    sa.Column('capitalization_frequency', sa.String(length=50), nullable=True),
    sa.Column('interest_to_separate_account', sa.Boolean(), nullable=False),
    sa.Column('interest_to_deposit_body', sa.Boolean(), nullable=False),
    sa.Column('nominal_rate_only', sa.Boolean(), nullable=False),
    sa.Column('effective_rate_supported', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['variant_id'], ['deposit_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('variant_id', 'code', name='uq_interest_scheme_variant_code')
    )
    op.create_index(op.f('ix_deposit_interest_schemes_code'), 'deposit_interest_schemes', ['code'], unique=False)
    op.create_index(op.f('ix_deposit_interest_schemes_variant_id'), 'deposit_interest_schemes', ['variant_id'], unique=False)
    op.create_table('deposit_rate_bonuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('bonus_type', sa.Enum('SUBSCRIPTION', 'SALARY', 'PENSION', 'SPEND', 'SAVINGS_BALANCE', 'PREMIUM_PACKAGE', 'PROMO', 'OTHER', name='bonus_type_enum'), nullable=False),
    sa.Column('bonus_value', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('is_percent_points', sa.Boolean(), nullable=False),
    sa.Column('stackable', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.CheckConstraint('bonus_value >= 0', name='ck_bonus_value_non_negative'),
    sa.ForeignKeyConstraint(['variant_id'], ['deposit_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bonus_variant_type', 'deposit_rate_bonuses', ['variant_id', 'bonus_type'], unique=False)
    op.create_index(op.f('ix_deposit_rate_bonuses_variant_id'), 'deposit_rate_bonuses', ['variant_id'], unique=False)
    op.create_table('deposit_variant_open_methods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('open_method_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['open_method_id'], ['deposit_open_methods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['deposit_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('variant_id', 'open_method_id', name='uq_variant_open_method')
    )
    op.create_index(op.f('ix_deposit_variant_open_methods_open_method_id'), 'deposit_variant_open_methods', ['open_method_id'], unique=False)
    op.create_index(op.f('ix_deposit_variant_open_methods_variant_id'), 'deposit_variant_open_methods', ['variant_id'], unique=False)
    op.create_table('deposit_base_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('interest_scheme_id', sa.Integer(), nullable=True),
    sa.Column('open_method_id', sa.Integer(), nullable=True),
    sa.Column('amount_from', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('amount_to', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('term_from_days', sa.Integer(), nullable=False),
    sa.Column('term_to_days', sa.Integer(), nullable=False),
    sa.Column('nominal_rate', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('effective_rate', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.CheckConstraint('amount_from >= 0', name='ck_base_rate_amount_from_non_negative'),
    sa.CheckConstraint('amount_to IS NULL OR amount_to >= amount_from', name='ck_base_rate_amount_to_gte_amount_from'),
    sa.CheckConstraint('effective_rate IS NULL OR effective_rate >= 0', name='ck_effective_rate_non_negative'),
    sa.CheckConstraint('nominal_rate >= 0', name='ck_nominal_rate_non_negative'),
    sa.CheckConstraint('term_from_days > 0', name='ck_base_rate_term_from_positive'),
    sa.CheckConstraint('term_to_days >= term_from_days', name='ck_base_rate_term_to_gte_term_from'),
    sa.ForeignKeyConstraint(['interest_scheme_id'], ['deposit_interest_schemes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['open_method_id'], ['deposit_open_methods.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['variant_id'], ['deposit_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('variant_id', 'interest_scheme_id', 'open_method_id', 'amount_from', 'amount_to', 'term_from_days', 'term_to_days', 'effective_from', name='uq_base_rate_slice')
    )
    op.create_index('ix_base_rates_lookup', 'deposit_base_rates', ['variant_id', 'interest_scheme_id', 'open_method_id', 'amount_from', 'amount_to', 'term_from_days', 'term_to_days', 'effective_from', 'effective_to'], unique=False)
    op.create_index(op.f('ix_deposit_base_rates_interest_scheme_id'), 'deposit_base_rates', ['interest_scheme_id'], unique=False)
    op.create_index(op.f('ix_deposit_base_rates_open_method_id'), 'deposit_base_rates', ['open_method_id'], unique=False)
    op.create_index(op.f('ix_deposit_base_rates_variant_id'), 'deposit_base_rates', ['variant_id'], unique=False)
    op.create_table('deposit_rate_bonus_conditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bonus_id', sa.Integer(), nullable=False),
    sa.Column('condition_type', sa.Enum('BOOLEAN', 'MIN_VALUE', 'ENUM', 'JSON_RULE', name='condition_type_enum'), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('operator', sa.String(length=20), nullable=False),
    sa.Column('value_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['bonus_id'], ['deposit_rate_bonuses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bonus_conditions_bonus_id', 'deposit_rate_bonus_conditions', ['bonus_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bonus_conditions_bonus_id', table_name='deposit_rate_bonus_conditions')
    op.drop_table('deposit_rate_bonus_conditions')
    op.drop_index(op.f('ix_deposit_base_rates_variant_id'), table_name='deposit_base_rates')
    op.drop_index(op.f('ix_deposit_base_rates_open_method_id'), table_name='deposit_base_rates')
    op.drop_index(op.f('ix_deposit_base_rates_interest_scheme_id'), table_name='deposit_base_rates')
    op.drop_index('ix_base_rates_lookup', table_name='deposit_base_rates')
    op.drop_table('deposit_base_rates')
    op.drop_index(op.f('ix_deposit_variant_open_methods_variant_id'), table_name='deposit_variant_open_methods')
    op.drop_index(op.f('ix_deposit_variant_open_methods_open_method_id'), table_name='deposit_variant_open_methods')
    op.drop_table('deposit_variant_open_methods')
    op.drop_index(op.f('ix_deposit_rate_bonuses_variant_id'), table_name='deposit_rate_bonuses')
    op.drop_index('ix_bonus_variant_type', table_name='deposit_rate_bonuses')
    op.drop_table('deposit_rate_bonuses')
    op.drop_index(op.f('ix_deposit_interest_schemes_variant_id'), table_name='deposit_interest_schemes')
    op.drop_index(op.f('ix_deposit_interest_schemes_code'), table_name='deposit_interest_schemes')
    op.drop_table('deposit_interest_schemes')
    op.drop_index(op.f('ix_deposit_fees_variant_id'), table_name='deposit_fees')
    op.drop_table('deposit_fees')
    op.drop_index(op.f('ix_deposit_early_termination_rules_variant_id'), table_name='deposit_early_termination_rules')
    op.drop_table('deposit_early_termination_rules')
    op.drop_index(op.f('ix_deposit_constraints_variant_id'), table_name='deposit_constraints')
    op.drop_index('ix_constraints_variant_type', table_name='deposit_constraints')
    op.drop_table('deposit_constraints')
    op.drop_index(op.f('ix_deposit_variants_product_id'), table_name='deposit_variants')
    op.drop_index(op.f('ix_deposit_variants_code'), table_name='deposit_variants')
    op.drop_table('deposit_variants')
    op.drop_index(op.f('ix_deposit_products_bank_id'), table_name='deposit_products')
    op.drop_table('deposit_products')
    op.drop_index(op.f('ix_deposit_open_methods_code'), table_name='deposit_open_methods')
    op.drop_table('deposit_open_methods')
    op.drop_index(op.f('ix_banks_slug'), table_name='banks')
    op.drop_table('banks')
    # ### end Alembic commands ###
